# Generated by Django 5.2.3 on 2025-06-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='seats_available',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
